 name: 'forge-action'
 description: 'Update Moldfile with forge'
 inputs:
   version:
     description: 'The version of forge to use'
     default: 'latest'
   build-context:
     description: 'The path to build the base Dockerfile'
   dockerfile:
     description: 'The base Dockerfile to generate Moldfile'
 runs:
   using: 'node20'
   main: 'dist/index.js'
