name: 'forge-action'
description: 'Update Moldfile with forge'
inputs:
  version:
    description: 'The version of forge to use'
    default: 'latest'
  working-directory:
    description: 'Working directory'
    default: '.'
  build-context:
    description: 'The path to build the base Dockerfile'
    required: true
  dockerfile:
    description: 'The base Dockerfile to generate Moldfile'
    required: true
  moldfile:
    description: 'The target Moldfile to update'
    required: true
  update-stye:
    description: |
      The way to update a Moldfile. Default "new-pr".
      new-pr: Create a new pull request with an updated Moldfile. If the event is "pull_request", the action add a comment to the original pull request to notify the new pull request created.
      direct-commit: Create an update commit and push it on the same branch.
    required: true
    default: 'new-pr'
  github-token:
    description: 'Need permission to write the repository'
  forge-install-token:
    description: 'Required while forge repository is private'
runs:
  using: 'node20'
  main: 'dist/index.js'
