on: [workflow_call]

jobs:
  debug:
    runs-on: ubuntu-latest
    name: Debug for forge-action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.3'
      - name: forge action step
        uses: ./ # Uses an action in the root directory
        id: forge
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
